const express = require("express")
const connectTodb = require("./config/mongodbConfig")
const userRouter = require("./routes/userRoutes")
const noteRouter = require("./routes/routes")
const app = express()
app.use(express.json())
connectTodb()
app.use("/api",userRouter)
app.use("/api",noteRouter)
app.listen(3000,()=>{
    console.log("port started")
})
